CONFIG_BT_BUF_ACL_TX_COUNT=20                              
CONFIG_BT_CONN_TX_MAX=10                                  
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8                        
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8                      